package com.stats.lolgg.model;

/**
 * 챔피언 영문명 변경
 * @author codingpoppy94
 * @version 1.0
 */
public enum ChampEnum {
    AATROX("Aatrox", "아트록스"),
    AHRI("Ahri", "아리"),
    AKALI("Akali", "아칼리"),
    AKSHAN("Akshan", "아크샨"),
    ALISTAR("Alistar", "알리스타"),
    AMUMU("Amumu","아무무"),
    ANNIE("Annie", "애니"),
    ANIVIA("Anivia","애니비아"),
    APHELIOS("Aphelios", "아펠리오스"),
    ASHE("Ashe", "애쉬"),
    AURELION_SOL("AurelionSol", "아우렐리온솔"),
    AZIR("Azir", "아지르"),
    BARD("Bard", "바드"),
    BELVETH("Belveth", "벨베스"),
    BLITZCRANK("Blitzcrank", "블리츠크랭크"),
    BRAND("Brand", "브랜드"),
    BRAUM("Braum", "브라움"),
    BRIAR("Briar", "브라이어"),
    CAITLYN("Caitlyn", "케이틀린"),
    CAMILLE("Camille", "카밀"),
    CASSIOPEIA("Cassiopeia", "카시오페아"),
    CHO_GATH("Chogath", "초가스"),
    CORKI("Corki", "코르키"),
    DARIUS("Darius", "다리우스"),
    DIANA("Diana", "다이애나"),
    DRAVEN("Draven", "드레이븐"),
    DR_MUNDO("DrMundo", "문도박사"),
    EKKO("Ekko","에코"),
    ELISE("Elise", "엘리스"),
    EVELYNN("Evelynn", "이블린"),
    EZREAL("Ezreal", "이즈리얼"),
    FIDDLESTICKS("Fiddlesticks","피들스틱"),
    FIORA("Fiora", "피오라"),
    FIZZ("Fizz", "피즈"),
    GALIO("Galio", "갈리오"),
    GAREN("Garen", "가렌"),
    GNAR("Gnar", "나르"),
    GRAGAS("Gragas", "그라가스"),
    GRAVES("Graves", "그레이브즈"),
    GANGPLANK("Gangplank","갱플랭크"),
    GWEN("Gwen", "그웬"),
    HECARIM("Hecarim", "헤카림"),
    HEIMERDINGER("Heimerdinger","하이머딩거"),
    HWEI("Hwei", "흐웨이"),
    ILLAOI("Illaoi", "일라오이"),
    IRELIA("Irelia", "이렐리아"),
    IVERN("Ivern","아이번"),
    JANNA("Janna", "잔나"),
    JARVAN_IV("JarvanIV", "자르반4세"),
    JAX("Jax", "잭스"),
    JAYCE("Jayce", "제이스"),
    JHIN("Jhin", "진"),
    JINX("Jinx", "징크스"),
    KAI_SA("Kaisa", "카이사"),
    KALISTA("Kalista", "칼리스타"),
    KARMA("Karma", "카르마"),
    KARTHUS("Karthus", "카서스"),
    KASSADIN("Kassadin", "카사딘"),
    KATARINA("Katarina", "카타리나"),
    KAYLE("Kayle", "케일"),
    KAYN("Kayn", "케인"),
    KENNEN("Kennen", "케넨"),
    KHA_ZIX("Khazix", "카직스"),
    KINDRED("Kindred", "킨드레드"),
    KLED("Kled", "클레드"),
    KOG_MAW("KogMaw", "코그모"),
    KSANTE("KSante", "크산테"),
    LEBLANC("Leblanc", "르블랑"),
    LEE_SIN("LeeSin", "리신"),
    LEONA("Leona", "레오나"),
    LILLIA("Lillia", "릴리아"),
    LISSANDRA("Lissandra", "리산드라"),
    LUCIAN("Lucian", "루시안"),
    LULU("Lulu", "룰루"),
    LUX("Lux", "럭스"),
    MALPHITE("Malphite", "말파이트"),
    MAOKAI("Maokai", "마오카이"),
    MISS_FORTUNE("MissFortune", "미스포츈"),
    MONKEY_KING("MonkeyKing", "오공"),
    MORDEKAISER("Mordekaiser", "모데카이저"),
    MORGANA("Morgana", "모르가나"),
    MASTER_YI("MasterYi","마스터이"),
    MALZAHAR("Malzahar","말자하"),
    MILIO("Milio","밀리오"),
    NAMI("Nami", "나미"),
    NASUS("Nasus", "나서스"),
    NAAFIRI("Naafiri","나피리"),
    NAUTILUS("Nautilus", "노틸러스"),
    NEEKO("Neeko", "니코"),
    NIDALEE("Nidalee", "니달리"),
    NOCTURNE("Nocturne", "녹턴"),
    NUNU("Nunu","누누"), //누누
    NILAH("Nilah","닐라"),
    OLAF("Olaf", "올라프"),
    ORIANNA("Orianna", "오리아나"),
    ORNN("Ornn", "오른"),
    PANTHEON("Pantheon", "판테온"),
    POPPY("Poppy", "뽀삐"),
    PYKE("Pyke", "파이크"),
    QIYANA("Qiyana","키아나"),
    QUINN("Quinn","퀸"),
    RAKAN("Rakan", "라칸"),
    RAMMUS("Rammus", "람머스"),
    REK_SAI("RekSai", "렉사이"),
    RELL("Rell", "렐"),
    RENEKTON("Renekton", "레넥톤"),
    RENGAR("Rengar", "렝가"),
    RUMBLE("Rumble", "럼블"),
    RYZE("Ryze", "라이즈"),
    RENATA_GLASC("Renata","레나타"),
    RIVEN("Riven","리븐"),
    SAMIRA("Samira", "사미라"),
    SEJUANI("Sejuani", "세주아니"),
    SENNA("Senna", "세나"),
    SERAPHINE("Seraphine", "세라핀"),
    SETT("Sett", "세트"),
    SHACO("Shaco", "샤코"),
    SHEN("Shen", "쉔"),
    SHYVANA("Shyvana","쉬바나"),
    SINGED("Singed", "신지드"),
    SION("Sion", "사이온"),
    SIVIR("Sivir", "시비르"),
    SKARNER("Skarner", "스카너"),
    SMOLDER("Smolder", "스몰더"),
    SONA("Sona","소나"),
    SORAKA("Soraka", "소라카"),
    SWAIN("Swain", "스웨인"),
    SYLAS("Sylas", "사일러스"),
    SYNDRA("Syndra","신드라"),
    TAHM_KENCH("TahmKench", "탐켄치"),
    TALIYAH("Taliyah", "탈리야"),
    TALON("Talon","탈론"),
    TARIC("Taric", "타릭"),
    TEEMO("Teemo", "티모"),
    THRESH("Thresh", "쓰레쉬"),
    TRISTANA("Tristana", "트리스타나"),
    TRUNDLE("Trundle", "트런들"),
    TRYNDAMERE("Tryndamere", "트린다미어"),
    TWISTED_FATE("TwistedFate", "트페"),
    TWITCH("Twitch", "트위치"),
    UDYR("Udyr","우디르"),
    URGOT("Urgot", "우르곳"),
    VARUS("Varus", "바루스"),
    VAYNE("Vayne", "베인"),
    VEIGAR("Veigar", "베이가"),
    VEL_KOZ("Velkoz", "벨코즈"),
    VEX("Vex", "벡스"),
    VI("Vi", "바이"),
    VIEGO("Viego", "비에고"),
    VIKTOR("Viktor", "빅토르"),
    VOLIBEAR("Volibear", "볼리베어"),
    WARWICK("Warwick", "워윅"),
    XAYAH("Xayah", "자야"),
    XERATH("Xerath", "제라스"),
    XIN_ZHAO("XinZhao", "신짜오"),
    YASUO("Yasuo", "야스오"),
    YONE("Yone", "요네"),
    YORICK("Yorick", "요릭"),
    YUUMI("Yuumi", "유미"),
    ZAC("Zac", "자크"),
    ZED("Zed", "제드"),
    ZERI("Zeri", "제리"),
    ZIGGS("Ziggs", "직스"),
    ZILEAN("Zilean", "질리언"),
    ZOE("Zoe", "조이"),
    ZYRA("Zyra", "자이라");

    private String englishChampName;
    private String koreanChampName;

    ChampEnum(String englishChampName,String koreanChampName){
        this.englishChampName = englishChampName;
        this.koreanChampName = koreanChampName;
    }

    public String getEnglishChampName() {
        return englishChampName;
    }

    public String getKoreanChampName() {
        return koreanChampName;
    }

    public static String getKoreanValue(String englishValue) {
        // System.out.println("englishValue: " +englishValue);
        for (ChampEnum mappingEnum : ChampEnum.values()) {
            if (mappingEnum.getEnglishChampName().toLowerCase().equals(englishValue)) {
                return mappingEnum.getKoreanChampName();
            }
        }
        return englishValue; 
    }
}
